name: Deploy Angular Frontend to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust to the branch you deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/CalTracker-frontend  # Path to your Angular frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --output-path=dist/CalTracker-frontend  # Ensure path matches angular.json

      - name: List dist contents
        run: ls -R dist/CalTracker-frontend

      - name: check current folder
        run: pwd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../dist/CalTracker-frontend  # Make sure this path matches the output path in the previous step
          keep_files: false  # Optional: keeps files on gh-pages not overwritten by new build
