name: Deploy Angular Frontend to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust to the branch you deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend/CalTracker-frontend  # Set working directory for Angular project

      - name: Build Angular project
        run: npm run build -- --configuration production
        working-directory: ./Frontend/CalTracker-frontend  # Set working directory for build

      - name: List dist contents
        run: ls -R ./Frontend/CalTracker-frontend/dist/CalTracker-frontend  # Verify contents of the dist folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Frontend/CalTracker-frontend/dist/CalTracker-frontend  # Path to the built app directory
          keep_files: false
