name: Deploy Angular Frontend to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust to the branch you deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend/CalTracker-frontend  # Set working directory for Angular project

      - name: Build Angular project
        run: npm run build
        working-directory: ./Frontend/CalTracker-frontend  # Set working directory for build

      - name: Create a publish directory
        run: mkdir -p ./gh-pages  # Create a temporary directory for publishing

      - name: Copy built files
        run: cp -R ./Frontend/CalTracker-frontend/dist/CalTracker-frontend/* ./gh-pages/
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages  # Publish from the temporary directory
          keep_files: false
